---
$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: '0.2'
useCache: true
useGitignore: true
dictionaryDefinitions:
  - name: cspell-words
    path: cspell-words.txt
    addWords: true
dictionaries:
  - cspell-words
language: en-US
ignorePaths:
  - '/.vscode/'
  - 'cspell-words.txt'
  - 'cspell.config.yaml'
  - '/LICENSE'
  - '.*'
  - 'cad/CO2-Ampel/CO2-Ampel-Flächen-V1-2-3D-BT.txt'
  - 'grafana-dashboards/*'
  - 'tests/testdata/*'
  - 'TODO.txt'
  - 'uv.lock'
  - 'wiring/*'
