{
 "title": "Electricity",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "CentPerWh", "query": "0.03320" }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Meter",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tasmota_MT681",
     "select": [
      [
       { "params": [ "watt" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "PV",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Shelly",
     "select": [
      [
       { "params": [ "watt_now" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "room::tag", "operator": "=", "value": "Balkon" }
     ]
    },
    { "expression": "$PV + $M", "type": "math" },
    {
     "expression": "$PV * ( $PV < $SumPos) + $SumPos * ($SumPos <= $PV)",
     "type": "math"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_room",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "room" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Shelly",
     "query": "SELECT mean(\"temperature\") FROM \"Raumklima\" WHERE $timeFilter GROUP BY time($__interval), \"device\" fill(null)",
     "select": [
      [
       { "params": [ "watt_last" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "room::tag", "operator": "!=", "value": "Balkon" }
     ]
    }
   ]
  },
  {
   "title": "Watt",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "Meter",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tasmota_MT681_min",
     "select": [
      [
       { "params": [ "watt" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    { "expression": "- $B", "type": "math" },
    {
     "alias": "HomeOffice",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Shelly",
     "select": [
      [
       { "params": [ "watt_now" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "room::tag", "operator": "=", "value": "Torben" }
     ]
    },
    {
     "alias": "Wohnzimmer",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Shelly",
     "select": [
      [
       { "params": [ "watt_now" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "room::tag", "operator": "=", "value": "Wohnzimmer" }
     ]
    },
    {
     "alias": "Wohnzimmer2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Shelly",
     "select": [
      [
       { "params": [ "watt_now" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "room::tag", "operator": "=", "value": "Plug5" }
     ]
    },
    { "expression": "$A + $B", "type": "math" },
    {
     "alias": "Plug4-Switch",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Shelly",
     "select": [
      [
       { "params": [ "watt_now" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "room::tag", "operator": "=", "value": "Plug4-Switch" }
     ]
    },
    {
     "alias": "Plug6",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Shelly",
     "select": [
      [
       { "params": [ "watt_now" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "room::tag", "operator": "=", "value": "Plug6" }
     ]
    }
   ]
  },
  {
   "title": "PV When First Watt",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "targets": [
    {
     "alias": "first 25W",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Shelly_PV_When_Watt3",
     "query": "SELECT mean(\"f_025W\") FROM \"inf\".\"Shelly_PV_When_Watt\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "f025W" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "first 50W",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Shelly_PV_When_Watt3",
     "query": "SELECT mean(\"f_025W\") FROM \"inf\".\"Shelly_PV_When_Watt\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "f050W" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "first 100W",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Shelly_PV_When_Watt3",
     "query": "SELECT mean(\"f_025W\") FROM \"inf\".\"Shelly_PV_When_Watt\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "f100W" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "first 200W",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Shelly_PV_When_Watt3",
     "query": "SELECT mean(\"f_025W\") FROM \"inf\".\"Shelly_PV_When_Watt\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "f200W" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "first 400W",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Shelly_PV_When_Watt3",
     "query": "SELECT mean(\"f_025W\") FROM \"inf\".\"Shelly_PV_When_Watt\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "f400W" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "first 600W",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Shelly_PV_When_Watt3",
     "query": "SELECT mean(\"f_025W\") FROM \"inf\".\"Shelly_PV_When_Watt\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "l600W" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "PV When Last Watt",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "targets": [
    {
     "alias": "last 25W",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Shelly_PV_When_Watt3",
     "query": "SELECT mean(\"f_025W\") FROM \"inf\".\"Shelly_PV_When_Watt\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "l025W" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "last 50W",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Shelly_PV_When_Watt3",
     "query": "SELECT mean(\"f_025W\") FROM \"inf\".\"Shelly_PV_When_Watt\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "l050W" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "last 100W",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Shelly_PV_When_Watt3",
     "query": "SELECT mean(\"f_025W\") FROM \"inf\".\"Shelly_PV_When_Watt\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "l100W" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "last 200W",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Shelly_PV_When_Watt3",
     "query": "SELECT mean(\"f_025W\") FROM \"inf\".\"Shelly_PV_When_Watt\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "l200W" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "last 400W",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Shelly_PV_When_Watt3",
     "query": "SELECT mean(\"f_025W\") FROM \"inf\".\"Shelly_PV_When_Watt\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "l400W" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "last 600W",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Shelly_PV_When_Watt3",
     "query": "SELECT mean(\"f_025W\") FROM \"inf\".\"Shelly_PV_When_Watt\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "l600W" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Savings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "Meter",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tasmota_MT681",
     "select": [
      [
       { "params": [ "watt" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "PV",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Shelly",
     "select": [
      [
       { "params": [ "watt_now" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "room::tag", "operator": "=", "value": "Balkon" }
     ]
    },
    {
     "alias": "HomeOffice",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Shelly",
     "select": [
      [
       { "params": [ "watt_now" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "room::tag", "operator": "=", "value": "Torben" }
     ]
    },
    {
     "alias": "Wohnzimmer",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Shelly",
     "select": [
      [
       { "params": [ "watt_now" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "room::tag", "operator": "=", "value": "Wohnzimmer" }
     ]
    },
    {
     "expression": "$PV * ( $PV < $SumPos) + $SumPos * ($SumPos <= $PV)",
     "type": "math"
    }
   ]
  },
  {
   "title": "Cent per 15min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ct" } },
   "targets": [
    { "expression": "$Saved * $CentPerWh /4", "type": "math" },
    { "expression": "$M_kWh * 1000 * $CentPerWh", "type": "math" }
   ]
  },
  {
   "title": "Savings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "alias": "Meter In",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "tasmota_MT681_day",
     "select": [
      [
       { "params": [ "kWh_total_in" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tz": "UTC"
    },
    {
     "alias": "Meter Out",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tasmota_MT681_day",
     "select": [
      [
       { "params": [ "kWh_total_out" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tz": "UTC"
    },
    {
     "alias": "PV",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Shelly_PV_day",
     "select": [
      [
       { "params": [ "delta" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    { "expression": "$PV - $Out", "type": "math" },
    { "expression": "$In + $Savings", "type": "math" }
   ]
  },
  {
   "title": "Cent per day",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "ct" } },
   "targets": [
    { "expression": "$kWh * 1000 * $CentPerWh", "type": "math" }
   ]
  }
 ]
}