{
 "title": "MT681",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "CentPerWh", "query": "0.03320" }
  ]
 },
 "panels": [
  {
   "title": "Watt",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Watt",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tasmota_MT681",
     "select": [
      [
       { "params": [ "watt" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Watt current in 10s freq",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "Watt",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tasmota_MT681",
     "select": [
      [
       { "params": [ "watt" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    { "expression": "($A>0) * $A", "type": "math" },
    { "expression": "-($A<0) * $A", "type": "math" }
   ]
  },
  {
   "title": "av Wh per min",
   "type": "timeseries",
   "description": "using spread function on total counters for in and out",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "Watt",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "tasmota_MT681_min",
     "select": [
      [
       { "params": [ "watt" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    { "expression": "$A * ($A>0)", "type": "math" },
    { "expression": "-($A * ($A<0))", "type": "math" }
   ]
  },
  {
   "title": "Totals",
   "type": "stat",
   "gridPos": { "h": 9, "w": 2, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "In",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tasmota_MT681_min",
     "select": [
      [
       { "params": [ "kWh_total_in" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Out",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tasmota_MT681_min",
     "select": [
      [
       { "params": [ "kWh_total_out" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "av Wh per 15min",
   "type": "timeseries",
   "description": "using spread function on total counters for in and out",
   "gridPos": { "h": 9, "w": 11, "x": 2, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "alias": "InDelta",
     "groupBy": [
      { "params": [ "15m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tasmota_MT681_min",
     "select": [
      [
       { "params": [ "kWh_total_in" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ]
    },
    {
     "alias": "OutDelta",
     "groupBy": [
      { "params": [ "15m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tasmota_MT681_min",
     "select": [
      [
       { "params": [ "kWh_total_out" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ]
    },
    { "expression": "$A * 4", "type": "math" },
    { "expression": "$B * 4", "type": "math" }
   ]
  },
  {
   "title": "Cent per 15min",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ct" } },
   "targets": [
    { "expression": "$A * 1000 * $CentPerWh", "type": "math" }
   ]
  },
  {
   "title": "av Wh per hour",
   "type": "timeseries",
   "description": "using spread function on total counters for in and out",
   "gridPos": { "h": 9, "w": 11, "x": 2, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "alias": "In",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tasmota_MT681_min",
     "select": [
      [
       { "params": [ "kWh_total_in" ], "type": "field" },
       {
        "params": [],
        "type": "spread"
       }
      ]
     ]
    },
    {
     "alias": "Out",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tasmota_MT681_min",
     "select": [
      [
       { "params": [ "kWh_total_out" ], "type": "field" },
       {
        "params": [],
        "type": "spread"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "kWh in and out",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "alias": "In kWh",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tasmota_MT681_min",
     "select": [
      [
       { "params": [ "kWh_total_in" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Out kWh",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tasmota_MT681_min",
     "select": [
      [
       { "params": [ "kWh_total_out" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "av Wh per 4h",
   "type": "timeseries",
   "description": "using spread function on total counters for in and out",
   "gridPos": { "h": 9, "w": 11, "x": 2, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "alias": "InDelta",
     "groupBy": [
      { "params": [ "4h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tasmota_MT681_min",
     "select": [
      [
       { "params": [ "kWh_total_in" ], "type": "field" },
       {
        "params": [],
        "type": "spread"
       }
      ]
     ]
    },
    {
     "alias": "OutDelta",
     "groupBy": [
      { "params": [ "4h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tasmota_MT681_min",
     "select": [
      [
       { "params": [ "kWh_total_out" ], "type": "field" },
       {
        "params": [],
        "type": "spread"
       }
      ]
     ]
    },
    { "expression": "$A / 4", "type": "math" },
    { "expression": "$B / 4", "type": "math" }
   ]
  },
  {
   "title": "kWh per day",
   "type": "timeseries",
   "description": "using spread function on total counters for in and out",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "alias": "In",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tasmota_MT681_day",
     "select": [
      [
       { "params": [ "kWh_total_in" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ]
    },
    {
     "alias": "Out",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tasmota_MT681_day",
     "select": [
      [
       { "params": [ "kWh_total_out" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Cent per day",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "ct" } },
   "targets": [
    {
     "alias": "In",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tasmota_MT681_day",
     "select": [
      [
       { "params": [ "kWh_total_in" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ]
    },
    { "expression": "$kWh * 1000 * $CentPerWh", "type": "math" }
   ]
  }
 ]
}